name: CI
on:
  push:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: corepack enable
    - run: pnpm install
    - run: pnpm build

    - run: pnpm test:node

    - run: pnpm test-server &
    - run: sleep 2

    - run: pnpm test:pkg

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: pnpm test:deno

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: pnpm test:bun

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright
        path: playwright-report
    - name: print artifact url
      if: always()
      run: echo 'https://mmkal.com/artifact/${{github.repository}}/${{github.run_id}}/playwright'
